### ISSUE TITLE
Simulation function is targeting wrong instrument

### ISSUE THREAD

**Issue by ewg215** [scott-vincent/instrument-panel#31]
Hello
First of all: Great work and very useful and easy to understand in its current modular state.

I did build for the PI and PC, panel and data server, and have it working correctly .

But since I plan to replicate my Mooney M20J panel I am playing around with the instrument faces and - obviously - with the scales. 
So I needed the '_**simulated value**_' feature that you thankfully considered from the very start.

In using it, I figured that something must be wrong with the order of the instruments as you **scroll through** them with the **up/down keys** and **change values** with **left/right/Num4/Num6**. 
-> So the instrument name and value (in the blue patch) is not going to the expected/stated instrument.

I thought that it must be just my build or my very minor modifications I have done, but a clean build (PI) or a direct repository download (Win) are doing exactly the same.

Can you check this on your setup and fix it for the 1.5.x forward?

BTW: My airspeed indicator is complete and really looks like the real thing that I have on the instrument panel of my Mooney 201. Next is the more severe 'engine monitor' instruments that contains Fuel, CHT, Oil Press., Oil Temp and Amp meter, all in ONE long instrument with 7 dials and hands (could be broken down in small individual instruments).

Thanks.
D. W.

**Comment by scott-vincent** [comment]
Hi, I simulated the values originally because I started working on the project before FS2020 was released. You are probably right that the simulated values don't work as expected any more as I have no reason to use them now so they don't get tested with my newer releases. What I would suggest is if you still wish to simulate values just do it in the Data Link program instead. You can force Connected = true and then set any variable to whatever value you wish. This is probably a lot easier than trying to use the simulated variables I originally created. Good luck and I hope your project goes well.

**Comment by scott-vincent** [comment]
I've had a quick look this morning and I see the problem. I will add the fix to future versions. If you want to fix your current version replace line 505 of instrument-panel/simvars.cpp with this code:

        if (strcmp(SimVarDefs[i][1], "string32") == 0) {
            offset += 4;
        }
        else {
            offset++;
        }

**Comment by ewg215** [comment]
Thanks, that works.
Somewhere along the way I lost the fuel gauge hands but I will find them
again.

Cheers
D.W.

**Comment by scott-vincent** [comment]
Done
