### ISSUE TITLE
Tutorial guide to install on raspberry 4

### ISSUE THREAD

**Issue by bidulle** [scott-vincent/instrument-panel#33]
Hi,
I use the version on Windows, it's perfect.
I want to use it with a raspberry, but I don't find a real information of how to do it.
which OS is recommended on Raspberry 4?
What should we install?
do we have to compile instrument-panel, or can we take the version in Release?
I have seen the procedure for allegro5, but I have not found where allegro5 is installed.
Sorry if my questions sound silly, I confess that I am not a Raspberry expert.
Thanks

**Comment by scott-vincent** [comment]
Ideal soultion would be to have an SD card image where it is all setup for you. I just don't have the time to do this currently. Also, I'm not sure exactly what the steps are as my system has evolved and gone through a lot of experimentation. Somebody needs to do this from scratch and document the steps. As you can tell, it's a lot more complicated on Raspberry Pi rather than windows due to OpenGL, especially with hardware acceleration, being in an evolving state on the Pi. The Pi 4 is already different from earlier Pi's.

**Comment by bidulle** [comment]
Does it mean that it's more easier with a PI 3B+?
I have both systems.

If I can help, I can try to do the tutorial, as soon as I am able to have something working

**Comment by scott-vincent** [comment]
Added a Quick Start on Rapsberry Pi section to the readme now.
