### ISSUE TITLE
Pico USB switchbox

### ISSUE THREAD

**Issue by alfawalidou** [scott-vincent/instrument-panel#60]
Hi Scott Vincent,

Thank you so much for your hard work and for sharing your valuable project with us.

I tested the RPi Pico USB joystick using the Adafruit HID library, but it wasn't detected by Datalink. 

Could you please clarify which Pico USB switchbox project you were referring to in your last release?

Thanks

**Comment by scott-vincent** [comment]
You're welcome. I haven't published the Pico USB switchbox project as it was just an experiment really. I did find a good way to send rotary encoder values though. I used CircuitPython with this joystick library:

https://circuitpython-joystickxl.readthedocs.io/en/latest/

and I applied the pull request on his Github to make it report 16-bit axis values. I wrote the Pico code to centre each axis on boot, then it just adds or subtracts 1 for the encoders and reports the absolute values as joystick axes instead of button presses. It means no encoder inputs get missed as you don't have to check for press/release cycles all the time and the axis works fine when 16-bit because it only adds/subtracts 1 for each encoder step so you never hit the extremities.

Data link just subtracts the current joystick axis value from the starting value to find out how much the encoder has been turned since data link was started. Works really well.

**Comment by alfawalidou** [comment]
I greatly appreciate the detailed explanation you provided. It has enhanced my understanding for this point. If it’s not too much, could you kindly share the content files associated with your Pico project, or compiled files such as the “boot”, “code”, and “/lib” directories?

Thanks.

**Comment by scott-vincent** [comment]
Sure. Pico USB Switchbox code added here:

https://github.com/scott-vincent/pico-usb-switchbox

**Comment by alfawalidou** [comment]
thank you so much
