### ISSUE TITLE
Automatic fit to screen on tablet as monitor (Spacedesk)

### ISSUE THREAD

**Issue by robert-dobre** [scott-vincent/instrument-panel#62]
Hello! 

First of all, many thanks! I was looking for something like this project for quite some time.

I am trying to run the instrument panel using my Samsung tablet and Spacedesk app. The app makes my tablet be detected as a monitor in Windows and everything is wireless. When I press m, the instrument panel is moved to the second monitor (i.e., the tablet) but it is not shown full screen. I looks like it should be full screen (I don't see a title bar or anything) but it does not fill the screen, it uses only a part. I tried changing the settings to match the resolution of the monitor as it is reported by Windows, but no luck. 

Spacedesk is nice because it is free and eaasy to use. I think if the app would fill the whole screen and resize the instruments accordingly to take the whole space, that would be great. Can this be made?

Thank you very much again!

Best regards,
Robert

**Comment by scott-vincent** [comment]
Hi Robert,

It doesn't automatically position all the instruments because it is designed to be displayed behind some plywood with circles cut out so instead it allows precise positioning of each instrument. All the settings are saved of course so once you get the layout correct it will obviously be remembered forever then. I have a tablet connected via Spacedesk in landscape mode and these settings work well for me.

{
  "Data Link": {
    "Host": "127.0.0.1",
    "Port": 52020,
    "Data Rate FPS": 20
  },
  "Monitor": {
    "StartOn": 2,
    "Fullscreen": true
  },
  "ASI": {
    "Enabled": true,
    "Position X": 10,
    "Position Y": 0,
    "Size": 380
  },
  "ADI": {
    "Enabled": true,
    "Position X": 410,
    "Position Y": 0,
    "Size": 380
  },
  "ALT": {
    "Enabled": true,
    "Position X": 810,
    "Position Y": 0,
    "Size": 380
  },
  "TC": {
    "Enabled": true,
    "Position X": 0,
    "Position Y": 410,
    "Size": 380
  },
  "HI": {
    "Enabled": true,
    "Position X": 410,
    "Position Y": 410,
    "Size": 380
  },
  "VSI": {
    "Enabled": true,
    "Position X": 810,
    "Position Y": 410,
    "Size": 380
  }
}

If you tablet is a different resolution you will obviously need to adjust the values accordingly. Mine is 1200 x 800. Also, if it displays on the wrong monitor change the value of "Monitor -> StartOn" to a different value.

Please also note it is not the optimal setup to run on the same machine as the one running your flight simulator. Ideally you want to use a secondary PC / Laptop / Raspberry Pi instead.

Good luck!
